./multi_mem_test 0  &
./multi_mem_test 1  &
./multi_mem_test 2  &
./multi_mem_test 3  &
./multi_mem_test 4  &
./multi_mem_test 5  &
./multi_mem_test 6  &
./multi_mem_test 7  &
./multi_mem_test 8  &
./multi_mem_test 9  &
./multi_mem_test 10 &
./multi_mem_test 11 &
./multi_mem_test 12 &
./multi_mem_test 13 &
#./multi_mem_test 14 &
#./multi_mem_test 15 &
#./multi_mem_test 16 &
#./multi_mem_test 17 &
#./multi_mem_test 18 &
#./multi_mem_test 19 &
#./multi_mem_test 20 &
#./multi_mem_test 21 &
#./multi_mem_test 22 &
#./multi_mem_test 23 &
#./multi_mem_test 24 &
#./multi_mem_test 25 &
#./multi_mem_test 26 &
#./multi_mem_test 27 &
#./multi_mem_test 28 &
#./multi_mem_test 29 &
#./multi_mem_test 30 &
#./multi_mem_test 31 &
